import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { JSX } from 'react';

const poppins = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${poppins.className} bg-[#171717] antialiased`}>
        {children}
      </body>
    </html>
  );
}
